name: Compile ESP32 CYD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Board Package
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          
      - name: Install Libraries
        run: |
          # Устанавливаем все необходимые библиотеки
          arduino-cli lib install "TFT_eSPI"
          arduino-cli lib install "XPT2046_Touchscreen"
          arduino-cli lib install "ESPping"
          # Если появятся ошибки с другими библиотеками, добавляйте их сюда по аналогии:
          # arduino-cli lib install "ИмяБиблиотеки"

      - name: Compile
        run: |
          # Компилируем проект
          arduino-cli compile --fqbn esp32:esp32:esp32 ./ESP32CYD
