name: Compile and Update Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Platform
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Libraries
        run: |
          arduino-cli lib install "TFT_eSPI"
          arduino-cli lib install "XPT2046_Touchscreen"
          arduino-cli lib install "ESPping"

      - name: Compile Project
        run: |
          # Замените ESP32CYD на имя папки, где лежит ваш .ino файл
          arduino-cli compile --fqbn esp32:esp32:esp32 ./ESP32CYD

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          body: "Автоматическая сборка из ветки main"
          prerelease: true
          files: |
            **/*.ino.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
